### ISSUE TITLE
Test deps setup

### ISSUE THREAD

**Issue by jasonkarns** [ztombol/bats-assert#9]
What's the expected setup for the test suite?  A simple git-clone does not put the test suite in a runnable state (58 of the 119 tests fail; presumably because bats-support is not available).

I think at the very least, there ought to be some documentation (CONTRIBUTING.md ?) for getting the test suite in a runnable state. Though preferably, the test suite should be runnable out of the box after a clean clone.

In a larger sense, I'm not sure that this test suite should use bats-support at all for its tests. What purpose is there in making bats-support necessary for this test suite? I think that makes things rather confusing since bats-support is a runtime dep of bats-assert in the first place. Making it a test dep as well is confusing.

**Comment by ztombol** [comment]
The test suite does not depend on `bats-support` or anything else for that matter (other than Bats, obviously). The library however does depend on `bats-support` as a **runtime dependency**. To test something you have to run it...

When the test suite [loads `bats-support`](https://github.com/ztombol/bats-assert/blob/master/test/test_helper.bash#L6) it does so in order to satisfy the tested library's runtime dependency.

Check `bats-support`'s source code, it only deals with "boring" output formatting and some error reporting. **`bats-support` helps writing libraries not test suites**. Probably that's why it got no scrutiny when it was still just a [Bats pull request](https://github.com/sstephenson/bats/pull/110).

The documentation on `bats-assert` clearly lists `bats-support` as a dependency and points to `bats-docs` for installation. In turn `bats-docs` does state that dependencies have to be installed manually when using the git installation method, while `npm` and `homebrew` take care of it automatically.

When I run the test suite without `bats-support` available, all tests fail. Are you sure everything is good in your environment? Are you sure it's not loading an outdated copy? Perhaps you have `$TEST_DEPS_DIR` set to a directory containing an outdated copy?

---

In other news. I've been planning to add:
- **Contribution guidelines:** Down to the commit message style.. I like consistency.
- **Library specification:** I always intended `bats-docs` to be a formal specification explicitely spelling out the expected behaviour.
- **Example of writing a new library:** Complete with a howto and the skeleton of a library.
- **Example of using the libraries:** Again, with a howto and a skeleton project.

I have a lot on my plate right now. That's why these haven't happened yet. That's why I'm slower at replying. I've been working on adding _super convenient (TM)_ temporary directory handling to `bats-file` and drawing up a roadmap proposal for Bats' future in the little time I have.
